services:
  - type: web
    name: voice-interview-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: default
    autoDeploy: true